version: '3.8'

services:
  satrio-dev:
    build: .
    container_name: satrio-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./content:/app/content:ro
      - ./scripts:/app/scripts:ro
    networks:
      - integrate

networks:
  integrate:
    external: true
