backend:
  name: github
  repo: satrijo/satrio
  branch: main
  base_url: https://satrio.dev
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string" }
      - label: "Article Language"
        name: "article_language"
        widget: "select"
        options:
          - { label: "Indonesian", value: "indonesian" }
          - { label: "English", value: "english" }
      - label: "AI Generated"
        name: "ai_generated"
        widget: "select"
        options:
          - { label: "AI Generated", value: "ai" }
          - { label: "Human Generated", value: "human" }
          - { label: "Hybrid", value: "hybrid" }
      - label: "Programming Language"
        name: "programming_language"
        widget: "select"
        required: false
        options:
          - { label: "", value: "" }
          - { label: "JavaScript", value: "JavaScript" }
          - { label: "Python", value: "Python" }
          - { label: "PHP", value: "PHP" }
          - { label: "TypeScript", value: "Typescript" }
          - { label: "Go", value: "Go" }
          - { label: "Java", value: "Java" }
          - { label: "Other", value: "Other" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "work"
    label: "Work Experience"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Start Date", name: "start_date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Name", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: false }
